nom: miam-server
MONGO_URL: ${{ secrets.MONGO_URL }}
MEAL_ROUTE: ${{ secrets.MEAL_ROUTE }}
ORDER_ROUTE: ${{ secrets.ORDER_ROUTE }}
ADMIN_ROUTE: ${{ secrets.ADMIN_ROUTE }}
SIGNUP: ${{ secrets.SIGNUP }}
MEALS_ROUTE_GET_ALL: ${{ secrets.MEALS_ROUTE_GET_ALL }}
MEALS_ROUTE_GET_ONE: ${{ secrets.MEALS_ROUTE_GET_ONE }}
MEALS_ROUTE_GET_FAM: ${{ secrets.MEALS_ROUTE_GET_FAM }}
MEALS_ROUTE_CREATE: ${{ secrets.MEALS_ROUTE_CREATE }}
MEALS_ROUTE_MODIFY: ${{ secrets.MEALS_ROUTE_MODIFY }}
MEALS_ROUTE_DELETE_ONE: ${{ secrets.MEALS_ROUTE_DELETE_ONE }}
MEALS_ROUTE_DELETE_ALL: ${{ secrets.MEALS_ROUTE_DELETE_ALL }}
SIGNUP_ROUTE: ${{ secrets.SIGNUP_ROUTE }}
LOGIN_ROUTE: ${{ secrets.LOGIN_ROUTE }}
GET_ADMINS_ROUTE: ${{ secrets.GET_ADMINS_ROUTE }}
SERVED_ORDER_ROUTE: ${{ secrets.SERVED_ORDER_ROUTE }}
GET_ORDERS_ROUTE: ${{ secrets.GET_ORDERS_ROUTE }}
GET_ONE_ORDER_ROUTE: ${{ secrets.GET_ONE_ORDER_ROUTE }}
GET_SERVED_ORDERS_ROUTE: ${{ secrets.GET_SERVED_ORDERS_ROUTE }}
GET_ONE_SERVED_ORDER_ROUTE: ${{ secrets.GET_ONE_SERVED_ORDER_ROUTE }}
DELETE_ORDER_ROUTE: ${{ secrets.DELETE_ORDER_ROUTE }}
DELETE_SERVED_ORDER_ROUTE: ${{ secrets.DELETE_SERVED_ORDER_ROUTE }}
